#
# Index config file for test dataset.
#
version: 0.4

index_id: test

doc_mapping:
  field_mappings:
    - name: id
      type: u64
      fast: true
    - name: group
      type: text
      fast: true
      tokenizer: raw
    - name: body
      type: text
      record: position
    - name: weight
      type: f64
    - name: timestamp
      type: datetime
      fast: true
      input_formats:
        - iso8601
      precision: seconds
  timestamp_field: timestamp

search_settings:
  default_search_fields: [body]
